### ISSUE TITLE
User can submit location

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="460" alt="Screenshot 2023-03-02 at 10 51 20 AM" src="https://user-images.githubusercontent.com/34325124/222523914-756a1075-ca5a-441f-9775-5e06e3495346.png">

<img width="546" alt="Screenshot 2023-03-02 at 10 51 43 AM" src="https://user-images.githubusercontent.com/34325124/222523988-a1e3883e-fc9d-411b-a6e9-0fd633293bb1.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create html layout so that it matches with the figma model.
- [x] Create the header with the corresponding cloud and sun images
- [x] Add input box that takes the users, zip code or city
- [x] Complete the HTML form using the appropriate responsive layout classes
   - [x]  Write css for mobile  device first
   - [x] Adjust styling to fluidly adapt to desktop
- [x] Make sure the input is required.
- [x] create a new data.js file with a variable of data and an empty object of "location" and an object of "locationid" and "nextlocationid"
- [x]  create a new main.js file 
- [x] create a function that renders a DOM tree of the column only displaying the weather of the current day and upcoming days
- [x] create a function that renders a DOM tree for the column containing the forecast of the day and display the return 
- [x] Add an input event listener to the City/Zip code input and assign that value to the parameter 'location' of the function 'submitLocation' 
- [x] Assign the value of the input to the object "location" and increment. by one 
- [x] Add a submit event listener to the form element that
  - [x]  Increments the "locationid" and "nextlocationid" 
 - [x] Add a click event listener to the container only with the current days weather so that (mobile only):
   - [x] Have it switch to the forecast render
- [x] Add an event listener to the return button that (mobile only):
  - [x] Returns the user to the weather render 
- [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
