### ISSUE TITLE
Feature 2: User can check the weather for the week

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the weather for the week below the current forecast
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A table displaying the weather for each day of the week, with an icon visualizing the weather
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="258" alt="Screenshot 2023-03-03 at 9 26 19 AM" src="https://user-images.githubusercontent.com/34325124/222787323-edae067f-99c4-4327-8bc1-d961ed96f0ba.png">
<img width="657" alt="Screenshot 2023-03-03 at 9 27 14 AM" src="https://user-images.githubusercontent.com/34325124/222787436-6335ba77-1cb5-4780-94b1-0540fb45f8b8.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] inside the DOM tree of the additional forecast create a new div
  - [x] create a ul element with the class name 'weekly-weather'
  - [x] create a for loop that iterates through the days of the week and only pull the next 6 days after the current day being displayed
  - [x] Assign each those values to their own li and append them to the ul with the class 'weekly-weather'
- [x] add appropriate styling to both desktop and mobile view
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
