### ISSUE TITLE
Feature 3: User can view weather alerts 

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view current weather alerts
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Below the current forecast and the weekly weather the user will be able to see the current weather alerts 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="212" alt="Screenshot 2023-03-03 at 9 37 42 AM" src="https://user-images.githubusercontent.com/34325124/222789635-1b44dde9-47a5-4572-9d88-d08935a672d1.png">
<img width="503" alt="Screenshot 2023-03-03 at 9 38 07 AM" src="https://user-images.githubusercontent.com/34325124/222789743-d3df7fa5-56e3-42d0-ad50-db6b6dfeb8c9.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Below the DOM tree for the weekly weather create a new div with the class name 'weather-alerts'
  - [x] Create an h3 tag with the text content of alert and append it to the div 'weather-alerts'
  - [x] Below the weather alerts create another div with the class name 'alert' and append it to the div 'weather-alerts'
  - [x] inside the div 'alert' create an h4 tag with the text content 'Severity: ."severity"' and assign the class matching it's severity
  - [x] below the h4 tag create a p tag with the class name 'alert-text' with the text content of what the alert is.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
