### ISSUE TITLE
Feature 4: User can add more locations

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to add new locations
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to add new locations and view its current weather, forecast, weekly weather and weather alerts,
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="919" alt="Screenshot 2023-03-03 at 9 47 52 AM" src="https://user-images.githubusercontent.com/34325124/222791584-d3c8d707-3b2e-46af-9e4c-0a7c9877ef25.png">
<img width="582" alt="Screenshot 2023-03-03 at 9 48 14 AM" src="https://user-images.githubusercontent.com/34325124/222791636-732f85bc-64bf-4fa4-ac92-7f4b1ee16c47.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] inside the html file add a new button below the user entries with the class 'new-location' with the proper css styling to replicate the figma
- [x] next to the form enter button add a cancel button with the class 'cancel-button'
- [x] add an event listener to the button 'cancel-button' that:
  - [x]  returns the user back to the entry screen and hides the entry form
- [x] add an event listener to the button 'new-location' to have the form be displayed once again.
  - [x] have the new button hidden while in the new form
- [x] have the new entry append beneath the last entry 
- [x] void reoccurring entries
- [x] hide the new entries current forecast only on deskop and only allow it to be viewed when the current weather is clicked
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
