### ISSUE TITLE
Feature 5: User can delete a location

### ISSUE THREAD

**Issue by Lambpato** [Lambpato/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can delete a location
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

when a user double clicked one the current weather, a trash icon will be displayed that will allow the user to delete the location once clicked
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="582" alt="Screenshot 2023-03-03 at 10 04 14 AM" src="https://user-images.githubusercontent.com/34325124/222794595-e3af25c0-78b1-4930-ac2c-41cecd66c302.png">
<img width="639" alt="Screenshot 2023-03-03 at 10 04 26 AM" src="https://user-images.githubusercontent.com/34325124/222794630-6765b9e5-2678-4764-9bba-a59592df3ab5.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a new icon on the top right of current weather that is initially hidden
- [x] update the new entry button so that:
  - [x] it  displays a new button with an icon of a trashcan
- [x] add an event listener 'click' to the trash can button that
  - [x]  will delete the location that has been double clicked
  - [x] if all entries have been deleted display the entry form as well as the header
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
